name: Push to huggingface

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check LFS
        uses: ./.github/actions/size.yml
      - name: Push to HF
        uses: ./.github/actions/sync.yml
